services:
  metadata-ingestion-service:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: metadata-ingestion-service

    ports:
      - "8080:8080"

    environment:
      HTTP_PORT: "8080"
      WORKER_COUNT: "4"
      JOB_QUEUE_SIZE: "100"
      SINK_TYPE: "console"
      OUTPUT_FILE: "/tmp/metadata.json"
      OPENSEARCH_URL: "http://opensearch:9200" 
      OPENSEARCH_INDEX: "metadata"

    restart: unless-stopped